const COUNTRY_CURRENCY: Record<string, string> = {
  AE: 'AED',
  ARE: 'AED',
  AU: 'AUD',
  AUS: 'AUD',
  AT: 'EUR',
  AUT: 'EUR',
  BE: 'EUR',
  BEL: 'EUR',
  BR: 'BRL',
  BRA: 'BRL',
  CA: 'CAD',
  CAN: 'CAD',
  CH: 'CHF',
  CHE: 'CHF',
  CN: 'CNY',
  CHN: 'CNY',
  DE: 'EUR',
  DEU: 'EUR',
  DK: 'DKK',
  DNK: 'DKK',
  EG: 'EGP',
  EGY: 'EGP',
  ES: 'EUR',
  ESP: 'EUR',
  FI: 'EUR',
  FIN: 'EUR',
  FR: 'EUR',
  FRA: 'EUR',
  GB: 'GBP',
  GBR: 'GBP',
  GH: 'GHS',
  GHA: 'GHS',
  GR: 'EUR',
  GRC: 'EUR',
  HK: 'HKD',
  HKG: 'HKD',
  IE: 'EUR',
  IRL: 'EUR',
  IN: 'INR',
  IND: 'INR',
  IT: 'EUR',
  ITA: 'EUR',
  JP: 'JPY',
  JPN: 'JPY',
  KE: 'KES',
  KEN: 'KES',
  KR: 'KRW',
  KOR: 'KRW',
  MX: 'MXN',
  MEX: 'MXN',
  NG: 'NGN',
  NGA: 'NGN',
  NL: 'EUR',
  NLD: 'EUR',
  NO: 'NOK',
  NOR: 'NOK',
  NZ: 'NZD',
  NZL: 'NZD',
  PT: 'EUR',
  PRT: 'EUR',
  RW: 'RWF',
  RWA: 'RWF',
  SA: 'SAR',
  SAU: 'SAR',
  SE: 'SEK',
  SWE: 'SEK',
  SG: 'SGD',
  SGP: 'SGD',
  TZ: 'TZS',
  TZA: 'TZS',
  UG: 'UGX',
  UGA: 'UGX',
  US: 'USD',
  USA: 'USD',
  ZA: 'ZAR',
  ZAF: 'ZAR',
  ZM: 'ZMW',
  ZMB: 'ZMW',
};

const COUNTRY_NAME_CURRENCY: Record<string, string> = {
  AUSTRALIA: 'AUD',
  AUSTRIA: 'EUR',
  BELGIUM: 'EUR',
  BRAZIL: 'BRL',
  CANADA: 'CAD',
  CHINA: 'CNY',
  DENMARK: 'DKK',
  EGYPT: 'EGP',
  FINLAND: 'EUR',
  FRANCE: 'EUR',
  GERMANY: 'EUR',
  GHANA: 'GHS',
  GREECE: 'EUR',
  INDIA: 'INR',
  IRELAND: 'EUR',
  ITALY: 'EUR',
  JAPAN: 'JPY',
  KENYA: 'KES',
  MEXICO: 'MXN',
  NETHERLANDS: 'EUR',
  NIGERIA: 'NGN',
  NORWAY: 'NOK',
  NEWZEALAND: 'NZD',
  PORTUGAL: 'EUR',
  RWANDA: 'RWF',
  'SAUDI ARABIA': 'SAR',
  SINGAPORE: 'SGD',
  SOUTHAFRICA: 'ZAR',
  SWEDEN: 'SEK',
  SWITZERLAND: 'CHF',
  TANZANIA: 'TZS',
  UGANDA: 'UGX',
  'UNITED KINGDOM': 'GBP',
  'UNITED STATES': 'USD',
  ZAMBIA: 'ZMW',
};

export function currencyForCountry(country: string | null | undefined): string {
  const normalized = (country || '').trim().toUpperCase();
  if (COUNTRY_CURRENCY[normalized]) return COUNTRY_CURRENCY[normalized];

  const compactName = normalized.replace(/[^A-Z]/g, '');
  if (COUNTRY_NAME_CURRENCY[normalized]) return COUNTRY_NAME_CURRENCY[normalized];
  if (COUNTRY_NAME_CURRENCY[compactName]) return COUNTRY_NAME_CURRENCY[compactName];

  return 'USD';
}
